### ISSUE TITLE
Getting this to work and with Private Groups

### ISSUE THREAD

**Issue by Kpudlo** [franciskim/slackslime#5]
Hello @franciskim! I'm new to npm and have gotten it installed and updated to the latest version. However I'm having trouble getting slackslime to actually run.

As it stands I have the following setup ~/node_modules/yahar/node_modules/slackbotapi

When I run the code nodejs slackslime token1 token2 I get an error:
`TypeError: Cannot read property 'id' of null
    at slackAPI.<anonymous> (/home/cheeseburger/node_modules/yahar/slackslime.js:33:65)
    at slackAPI.emit (/home/cheeseburger/node_modules/yahar/node_modules/slackbotapi/node_modules/eventemitter3/index.js:116:35)
    at /home/cheeseburger/node_modules/yahar/node_modules/slackbotapi/lib/index.js:80:22
    at WebSocket.<anonymous> (/home/cheeseburger/node_modules/yahar/node_modules/slackbotapi/lib/index.js:215:24)
    at WebSocket.EventEmitter.emit (events.js:98:17)
    at Receiver.ontext (/home/cheeseburger/node_modules/yahar/node_modules/slackbotapi/node_modules/ws/lib/WebSocket.js:841:10)
    at /home/cheeseburger/node_modules/yahar/node_modules/slackbotapi/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/home/cheeseburger/node_modules/yahar/node_modules/slackbotapi/node_modules/ws/lib/Receiver.js:371:5)
    at /home/cheeseburger/node_modules/yahar/node_modules/slackbotapi/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/home/cheeseburger/node_modules/yahar/node_modules/slackbotapi/node_modules/ws/lib/Receiver.js:347:3)`

The weird thing is when I run the sample tokens in the readme.MD it finishes without any errors. Is there something I'm missing in what needs to be done? I also have the same channel name for both slacks

**Comment by Kpudlo** [comment]
Update: I was able to get it to work finally using pm2. However my current issue is that it doesn't pull from private groups, only channels. I'm working on trying to get rework the code so that it is using some of the group features, but it's just finding the right lines to convert, if I figure it out, I'll share it :)

**Comment by Kpudlo** [comment]
Ok so I did get this to work, I had to edit a few lines. Attached is the code I have now

`````` /*
 https://github.com/franciskim/slackslime
 by Francis Kim @ franciskim.co

 how to run from the shell:
 nodejs [channel name] [RTM API token 1] [RTM API token 2] [RTM API token 3] [more tokens]

 for example:
 nodejs devchat xoxb-1111111111-xxx xoxb-2222222222-xxx xoxb-3333333333-xxx

 or for PM2:
 pm2 start slackslime.js -- devchat xoxb-1111111111-xxx xoxb-2222222222-xxx xoxb-3333333333-xxx
*/

var slackAPI = require('slackbotapi');

var slackslime = {
    channelName: process.argv[2],
    tokens: process.argv.slice(3),
    connectedTeams: 0
};

var slacks = new Array(); // slack connections get stored here

slackslime.tokens.forEach(function(token, i) {
    slacks[i] = new slackAPI({
        'token': token,
        'logging': true, // necessary for debug output
        'autoReconnect': true
    });

    slacks[i].on('hello', function(data) {
        this.groupId = this.getGroup(slackslime.channelName).id;
        slackslime.connectedTeams++;
    });

    slacks[i].on('close', function(data) {
        slackslime.connectedTeams--;
    });

    slacks[i].on('message', function(data) {
        var self = this;
        var user = self.getUser(data.user);
        var teamName = self.slackData.team.name;
        var group = self.getGroup(data.channel);

        if(typeof data.text === 'undefined' || data.subtype === 'bot_message' || !group || group.name !== slackslime.channelName) {
            return;
        }

        if(user) {
            data.username = user.name;
            data.iconUrl = user.profile.image_48;
        }

        if(data.text.charAt(0) === '!') {
            // bot/channel commands should go here
            // split the command and its arguments into an array
            var command = data.text.substring(1).split(' ');

            switch(command[0].toLowerCase()) {
                case "list":
                    // send a list of all users on every chat and send via DM/PM
                    var message = '', awayCount = 0, activeCount = 0, userCount = 0;

                    slacks.forEach(function(s) {
                        s.reqAPI('groups.info', {channel: s.groupId}, function(d) {
                            if(d.ok) {
                                d.group.members.forEach(function(user) {
                                    if(s.getUser(user)) {
                                        var status = ':question:';
                                        userCount++;

                                        if(s.getUser(user).presence === 'active') {
                                            status = ':large_blue_circle:';
                                            activeCount++;
                                        }

                                        if(s.getUser(user).presence === 'away') {
                                            status = ':white_circle:';
                                            awayCount++;
                                        }

                                        message += status + ' `' + s.slackData.team.name + '` ' + s.getUser(user).name + '\n';
                                    }
                                })
                            }
                        });
                    });

                    self.sendPM(data.user,
                        '```Gathering a list of users, please wait...\nBlue = Active   White = Away```'
                    );

                    setTimeout(function() {
                        self.sendPM(data.user,
                            message + '```Active: ' + activeCount + '   Total: ' + userCount + '   Teams: '
                            + slackslime.connectedTeams + '```'
                        );
                    }, 2000); // 2 second default wait
                    break;
            }
        }

        else if(!data.subtype) {
            // this is a normal user message, send to other teams
            var message = {
                channel: slackslime.channelName,
                text: data.text,
                username: data.username + ' @ ' + teamName,
                icon_url: data.iconUrl,
                unfurl_links: true,
                unfurl_media: true
            };

            slacks.forEach(function(slack) {
                if(slack.token !== self.token) {
                    slack.reqAPI('chat.postMessage', message);
                }
            })
        }
    });

    slacks[i].on('file_shared', function(data) {
        // send the shared file to other teams
        // shared files in public channels already have a public URL (!)
        // todo: ask if the file should be shared
        var self = this;
        var user = self.getUser(data.file.user);
        var teamName = self.slackData.team.name;
        var channel = self.getChannel(data.file.channels.splice(-1)[0]); // https://api.slack.com/types/file

        if(channel.name !== slackslime.channelName) {
            return;
        }

        if(user) {
            data.username = user.name;
            data.iconUrl = user.profile.image_48;
        }

        var message = {
            channel: slackslime.channelName,
            text: '*' + data.file.title + '* ' + data.file.url,
            username: data.username + ' @ ' + teamName,
            icon_url: data.iconUrl,
            unfurl_links: true,
            unfurl_media: true
        };

        slacks.forEach(function(slack) {
            if(slack.token !== self.token) {
                slack.reqAPI('chat.postMessage', message);
            }
        })
    });
});
``````

**Comment by franciskim** [comment]
@Kpudlo thanks! 👍
